import QRCode from 'qrcode';

export async function generatePaymentQRCode(
  bankName: string,
  accountName: string,
  accountNumber: string,
  amount: number,
  currency: string,
  invoiceNumber: string
): Promise<string> {
  // Format standard payment payload
  const payload = `Payment to:
Bank: ${bankName || 'N/A'}
Account Name: ${accountName || 'N/A'}
Account Number: ${accountNumber || 'N/A'}
Amount: ${currency}${amount.toLocaleString()}
Reference: ${invoiceNumber}

Generated by LevFlow V3 - Invoice with impact`;

  try {
    const dataUrl = await QRCode.toDataURL(payload, {
      margin: 1,
      width: 256,
      color: {
        dark: '#1e293b', // slate-800
        light: '#f8fafc', // slate-50
      },
    });
    return dataUrl;
  } catch (err) {
    console.error('Failed to generate QR Code:', err);
    return '';
  }
}
